# Generated by Django 5.0.1 on 2024-01-23 22:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ACTION', 'Action'), ('DRAMA', 'Drama'), ('PODCAST', 'Podcast'), ('DOCUMENTARY', 'Documentary')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=5)),
                ('description', models.TextField()),
                ('Media', models.FileField(upload_to='upload/media/')),
                ('date_added', models.DateTimeField(default=datetime.datetime.today)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.category')),
            ],
        ),
    ]
